"""rename address

Revision ID: 60918cb7a572
Revises: 3685c8923277
Create Date: 2026-01-18 11:42:10.618293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60918cb7a572'
down_revision = '3685c8923277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
